### ISSUE TITLE
RtMidi prevents another application to read/write to opened device

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtmidi#102]
Hi,

I'm having an issue with RtMidi that I don't know if it is a limitation or something I'm failing to prevent. I have an app that lists all available midi devices. During this process I open each one of them with RtMidi. When this app is running and if I open another audio application, let's say, Ableton Live, the devices become unavailable for Ableton Live. When RtMidi opens a device, does it block the access by other audio/midi applications?

Thx

**Comment by radarsat1** [comment]
I don't see anything in particular in MidiInCore :: openPort() (RtMidi.cpp) that is setting any exclusivity flags, but I'm unfamiliar with the expected behaviour.  Are you opening them and keeping them open?  Or do you mean that they stay reserved after you close them? Is it normal for more than one application to be able to open the same CoreMIDI port?  Is it for reading or writing?  (receiving midi or sending midi?)

For reference, the following functions are called during openPort()
* MIDIInputPortCreate
*  MIDIGetSource( portNumber )
* MIDIPortConnectSource

**Comment by sinosoidal** [comment]
The problem is that if I instantiate a RtMidi In or Out and open the port, it becomes unavailable on Ableton Live. Curiously only the external usb midi devices ports become unavailable, since the virtual (loopMidi) and the Microsoft GS Wavetable Synth are kept available.

Yes, it is supposed for several different midi applications to have a access to midi ports simultaneously.

This is what I do in order to open a specific in port in this case:

    void IMidiDevice::openIn()
    {
        RtMidiIn *port = new RtMidiIn();

        uint i=0;

        for (; i<port->getPortCount(); i++)
        {
            if (QString::fromUtf8(port->getPortName(i).c_str()).compare(_name)==0)
        }

        if (i<port->getPortCount())
        {
            try
            {
                  port->openPort(i);
                  port->setCallback(&midiInCallback, (void*)this);
                  port->ignoreTypes(false, false, false);
                  _in = port;
            }
            catch (RtMidiError &error)
            {
                Q_UNUSED(error)
            }
        }
    }

**Comment by radarsat1** [comment]
I can't answer to,

> Yes, it is supposed for several different midi applications to have a access to midi ports simultaneously.

as I can't see this in any documentation, but perhaps it's the expected OS X user experience, I don't know.  In that case you'd need to find out if there is an exclusivity flag to set or unset somewhere in the CoreMIDI API.

However, otherwise, looking at your program you seem to be leaving 'port' allocated (and possibly open) after this function returns, even if there is an RtMidiError.  Perhaps you should call closePort() and/or delete the RtMidiIn object either in the catch() or at the end of the function.

**Comment by radarsat1** [comment]
Btw I think that wrapping the pointer in std::shared_ptr would take care of both ensuring the port is closed and freeing the memory.

**Comment by sinosoidal** [comment]
This is a Windows issue. I don't have problems in Mac. I have added additional debug to RtMidi and found the following. When RtMidi tries to open a port that is already open in Ableton Live, it returns MMSYSERR_NOMEM error. I have found someone with the same problem two years ago but it seems he didn't find an answer too: http://stackoverflow.com/questions/27407784/mmsyserr-nomem-when-calling-midiinopen-only-when-other-midi-apps-are-open#_=_

This really seems odd. Any professional audio software is able to deal with several connected midi devices at the same time.

**Comment by radarsat1** [comment]
Oh I see, sorry I don't know why I assumed Mac.  Unfortunately I don't know the answer and can't test it.  A bit of googling makes me wonder what would happen if you force it to use device -1?  (the midi mapper)

http://midi.teragonaudio.com/tech/lowmidi.htm

If that works (or any other info on that page turns out to be useful..) maybe it should be supported by the API somehow.

**Comment by sinosoidal** [comment]
From what I see in that document, one must open the device, write to it and close it right away when no longer needed. I didn't knew this and in mac doesn't seem to be a problem. In my previous implementation I was only opening a device when it was selected. Curiously, this is not an issue for virtual midi ports created, for instance by loopMidi. I guess that, if this is necessary, it should be implemented in RtMidi so it can facilitate it' usage. I will try to refactor my code to open the port everytime I want to write anything to it and then close it. I will let you know the outcome.

**Comment by sinosoidal** [comment]
Regarding MidiMapper, I don't want to rely in a feature that is controlled by the operating system. I want my app to list all available midi devices so the user can select which one is best for him.

**Comment by Boddlnagg** [comment]
According to https://blogs.windows.com/buildingapps/2016/09/21/midi-enhancements-in-windows-10, the Windows MIDI API used by RtMidi does not support multi-client use (i.e., opening the same port from multiple clients simultaneously): 

> One great feature of the new API is that it is multi-client. As long as all apps with the port open are using the Windows 10 UWP MIDI API and not the older Win32 MME or DirectMusic APIs, they can share the same device. This is something the older APIs don’t handle without custom drivers and was a common request from our partners and customers.

So starting in Windows 10, there is the new UWP API (WinRT) that does handle it, but it's not supported by RtMidi. Apparently, there once was an implementation of a [Windows backend using Kernel Streaming](https://github.com/thestk/rtmidi/tree/winks) (yet another API) which has been [removed](https://github.com/thestk/rtmidi/commit/d07f6011cfdb3ba59cbd409b7005d5676cdca4d4) because it never worked correctly.

The following forum thread also has some information about this problem: https://forum.juce.com/t/windows-multiple-client-usb-midi-drivers/10766, and it even [references](https://forum.juce.com/t/windows-multiple-client-usb-midi-drivers/10766/3) the Kernel Streaming implementation in RtMidi.

**Comment by sagamusix** [comment]
In addition to what @Boddlnagg said: There are _very_ few, device-specific Windows MIDI drivers that allow multiple applications to access the same MIDI port (e.g. the driver for ESI's M8U XL interface). All other drivers can only allow one application at a time to access a device. The new Windows 10 API helps in this regard, but obviously only on Windows 10.

**Comment by garyscavone** [comment]
Seems like this has been addressed ... perhaps someone can work on supporting the new WinRT API in RtMidi?
