### ISSUE TITLE
Documentation bug: Can callbacks overlap?

### ISSUE THREAD

**Issue by mcclure** [thestk/rtmidi#194]
The documentation https://www.music.mcgill.ca/~gary/rtmidi/ says "The RtMidiIn class uses an internal callback function or thread to receive incoming MIDI messages from a port or device". The sample code further makes it obvious that the callbacks returned by RtMidiIn::setCallback() will be called on something other than the main thread.

I have two problems with this.

* In my opinion, the documentation for the setCallback function https://www.music.mcgill.ca/~gary/rtmidi/classRtMidiIn.html#a7590563461c7467608a4b3806406b32d should be explicit "the callback will be called on a thread specific to RtMidi" rather than it being implied elsewhere in the documentation. Otherwise this could be surprising to a reader unfamiliar with threading.

* The documentation as is leaves one big thing mysterious: *Do RtMidi callbacks occur on one thread or potentially many?* Or asked a different way: *Could two RtMidi callbacks overlap?* I see three possibilities:

    1. All RtMidi callbacks occur on a single thread.
    2. All callbacks associated with one port or one RtMidiIn occur on the same thread, but different ports may use different threads.
    3. There is no predictability, any two callbacks could occur on different threads.

    ...or maybe which of these possibilities is the case depends on which OS you're on.

    I think I need to know *which* of these possibilities to plan for. If it's possibility 3 but I assume it's possibility 1, I might write code with race conditions. But if it's possibility 3 but I assume it's possibility 1, I might waste time on defensive strategies that aren't necessary. I don't care which is truth but the documentation should tell me which to expect.

**Comment by garyscavone** [comment]
I'm not 100% sure I understand the confusion but I'd like to make the documentation as clear as possible, so I'll try to explain and perhaps you can point out where you think the documentation is unclear. Generally, RtMidi was designed to work with only one port / device at a time. Within a given instance of RtMidiIn, there is one spawned thread that acquires incoming messages. If a user callback is set (via the setCallback() function), then that function will be called from within the message acquisition thread when a new message arrives.

If you are using two different instances of RtMidi, there will be two different, independent threads. The two callbacks could certainly happen at different times because incoming messages from the two different ports will likely arrive at different times.

Perhaps you are attempting to use the same callback function for two different instances of RtMidiIn? That might work (never tried it) but I wonder if one call to the user callback might potentially be interrupted by a concurrent call to it? It would be safer to use two different callbacks and then merge the MIDI data into a common buffer for your application.

**Comment by mcclure** [comment]
> Within a given instance of RtMidiIn, there is one spawned thread that acquires incoming messages. If a user callback is set (via the setCallback() function), then that function will be called from within the message acquisition thread when a new message arrives. If you are using two different instances of RtMidi, there will be two different, independent threads.

This is exactly what I needed to know. It would be helpful if this exact text were in the documentation.
