### ISSUE TITLE
Change RtMidiCallback to be an alias of std::function

### ISSUE THREAD

**Issue by michallaskowski** [thestk/rtmidi#43]
Hi, 
I would like to use lambdas as an RtMidiCallback. To do it for me all it took was to change RtMidiCallback typedef to:
```using RtMidiCallback = std::function<void(double timeStamp, std::vector<unsigned char> *message, void *userData)>;```
Although a compiler would need to support at least c++11 - I do not know but maybe it could be a problem for someone. Or maybe there is another way?
If you want I can create a patch or pull request, though it would be a small one.
Cheers,
Michal

**Comment by radarsat1** [comment]
You're right, this means having a dependency on C++11, which is probably a show stopper.  Otherwise you can try weird preprocessor tricks to discover std::function support, but this can get tricky and unreliable.  The more or less "right" way to deal with this imho is to provide the callback as a template parameter in the API.  Then the hidden (.cpp) parts of the code should be the only place where a specific choice is made about how to _store_ the function, and _there_ you can choose between storing a normal pointer or using an std::function, etc.  But to keep the API uniform to any version of C++, the setCallback() function should simply take a template parameter for a callable.

That said, I think there are relatively few cases where it's worth this complexity just to support lambdas.  Any program that grows to a certain size will need more than a short one-liner for the callback.  With a template argument you can equally provide a normal function, or an object with operator() for example.

**Comment by michallaskowski** [comment]
Well, for now I can live with standard c-style callback, rewriting the code as a template would take more time for me than I would like.
Thanks for the thorough answer, closing.
