### ISSUE TITLE
"vector iterators incompatible

### ISSUE THREAD

**Issue by morganpackard** [thestk/rtmidi#51]
Hello rtmidi!
I get this error when running rtmidi on Windows:

```
 vector iterators incompatible
```

The error originates on line 344 in RtMidi.cpp, with this code: 

```
 std::vector<unsigned char> *bytes = &(inputData_.queue.ring[inputData_.queue.front].bytes);
 message->assign( bytes->begin(), bytes->end() ); // this is where the error happens
```

It looks to me like the `queue` object may be corrupt. The `size` is 1000, and `ringsize` is 1000, which I believe means the queue is full. However, `front` is 943 and `back` is 950, which I wouldn't expect if the queue was full. I think if the queue is full, `front` and `back` should be only one apart.

My first guess is that this is a thread safety issue that might be solved by using a mutex to safely access `inputData_.queue`. However, I know RTMidi has been used for a long time by lots of people, so it would surprise me if was really the issue.

The midi input example at http://www.music.mcgill.ca/~gary/rtmidi/ is quite straightforward. Is there anything tricky about midi input that I might have missed that would help to prevent the corruption of `inputData_.queue`?

![image](https://cloud.githubusercontent.com/assets/1010021/9088515/5b02cfd4-3b5e-11e5-8d3a-76b762f9141d.png)

**Comment by morganpackard** [comment]
My hunch appears to be correct. Adding a mutex to MidiQueue (and using it every time the queue is accessed) seems to fix the issue.

**Comment by radarsat1** [comment]
Can you say a thing or two about how you are detecting and testing the issue?  Adding a mutex may solve the issue but may also have implications for efficiency, so it's important to know more details.

**Comment by morganpackard** [comment]
Sure. Might be best to just look at this pull request I created: 
https://github.com/thestk/rtmidi/pull/52
Note -- the PR has debug code in it, so I don't think you should accept it. It's just an easy way to present the diff.

Basic way I determined that something spooky was going on was by creating a validate method on MidiQueue to make sure the front and the back and the size all made sense together. I call that method before and after the input queue gets modified. In my use case, the validation (without any mutex locking) generally fails within the first second of running.

I understand that locking on an audio thread is not a good idea. I think really you need a lock-free queue, which I have no idea how to make! The mutex approach works for me since I'm not actually generating audio in my application. Please let me know if I can do more to help.

**Comment by DouglasHeriot** [comment]
It’s interesting to see this. It’s not an issue I’ve seen though, as it only applies to the getMessage() method – I’ve been using the callback API, which doesn’t appear to use the queue at all.

This issue probably applies to all platforms – OS X, Windows and Linux, as (I think?) they would all receive MIDI on some background thread.

* Apart from the fact we’re not supposed to lock on real-time MIDI threads, I don’t know if we can use `std::mutex` as I don’t know if RtMidi tries to support older compilers still? (I would vote to drop earlier compilers and require C++11). Implementing locking cross-platform, without C++11 would be a real pain.

* I feel like implementing a cross-platform lock-free queue is beyond the scope of RtMidi.

Alternatively, maybe we should mark the getMessage API as deprecated, and force people to use the callback API instead? Then users can deal with making it thread safe using whatever APIs make the most sense on their platforms.

I have no idea how many people use getMessage vs callbacks. I guess maybe more people use callbacks, and therefore haven’t ran into this issue?

**Comment by radarsat1** [comment]
Sorry I never looked at this closely.  The FIFO implementation is definitely not thread-safe.  In particular the "size" variable is unnecessary, front-back should be enough.  It's possible for size and front to be incremented/decremented in the wrong order.  For this situation (single producer, single consumer) it should be replaced ideally with an atomic increment, it can be done wait-free. Probably this is better done with C++11 atomics.  A mutex would be a good interim measure, but again, I wouldn't want to do it without C++11 -- otherwise we have to implement mutexes differently on every operating system.

For me this is a good reason to move to C++11 after the next release.  An alternative would be boost, but don't particular want to depend on it: http://www.boost.org/doc/libs/1_53_0/doc/html/boost/lockfree/queue.html

Maybe it could be optional somehow.

In the meantime I think removing "size" should help.  I am concerned that I don't have an easy way to test this however.
