### ISSUE TITLE
Win10 and Microsoft GS Synth

### ISSUE THREAD

**Issue by ncassetta** [thestk/rtmidi#77]
Hello
I had trouble using the GS Synth in Win10 (it gave an error when opening the port).
I googled a while and found this, which solved my problem:
http://stackoverflow.com/questions/31752786/midioutopen-on-windows-10-using-microsoft-gs-wavetable-synth-fails
I added a line to my code and the synth now plays MIDI data, however I think it could be managed directly in RtMidi.
Thanks for your attention
Nicola Cassetta

**Comment by sagamusix** [comment]
Note that while adding the call to `CoInitializeEx` solves the problem, it creates a dependency to a library the RtMidi user might not be depending on yet (Ole32), which makes compilation more complicated - especially since not every RtMidi user needs access to the GS Synth. Most GUI applications already link Ole32 so for those it's not a problem anyway.
However, at the very least, this workaround should be documented in the RtMidi documentation that calling `CoInitializeEx` and linking Ole32 may be required on some systems to make this work.

**Comment by garyscavone** [comment]
The configure scripts for STK and RtAudio already add a link for ole32. Is that is all that is required (in addition to the CoInitializeEx call)?

**Comment by sagamusix** [comment]
In addition to `CoInitializeEx`, `CoUninitialize` must also be called when shutting down the thread where the initialization happened (see the MSDN for more information). As far as I understand, all of this must happen in the same thread as the one that is going to call the MIDI API, so I think it's probably not a good idea to add those calls inside RtMidi itself, but add them to the examples provided with the library and encourage the users to add those calls to their programs if required. As mentioned, most programs will not require manual addition of those calls because they already use COM in one way or another.
