### ISSUE TITLE
docs link in the README is pointing to the wrong dir =)

### ISSUE THREAD

**Issue by Pomax** [thestk/rtmidi#93]
looks like the link to the docs is broken in the current README.md, pointing to a doc/html dir that does not exist.

**Comment by radarsat1** [comment]
If you do "make" the doc/html directory then exists. Doesn't work online. Know any good solution for that?  We could point it to http://www.music.mcgill.ca/~gary/rtmidi/annotated.html perhaps.

**Comment by Pomax** [comment]
hm, since they're docs, I'd honestly recommend to just run make and then commit the generated documentation into the repo. Alternatively you could make a `gh-pages` branch and copy the docs into that, then you can simply point to http://thestk.github.io/rtmidi but that's a chore to maintain.

**Comment by radarsat1** [comment]
No point with gh-pages since RtMidi's site is already hosted.  We can point it there, if Gary wants to change it.  In principle it shouldn't matter since users should be using the tarball from that page anyways, which contains the docs, which are hosted in the same place.  But making the README more clear might be a good idea, since github hosts it by default, and markdown links are sort of useless locally anyways.

**Comment by garyscavone** [comment]
I updated it to point to my website.
