### ISSUE TITLE
Overflow in timestamp computation

### ISSUE THREAD

**Issue by s-d-m** [thestk/rtmidi#98]
When compiling the library using clang's integer overflow sanitiser (`-fsanitize=integer`), it complains at runtime with the following error message:

```shell
RtMidi.cc:1275:11: runtime error: unsigned integer overflow: 1484769370242715 - 6872316419617283935 cannot be represented in type 'unsigned long long'
SUMMARY: AddressSanitizer: undefined-behavior RtMidi.cc:1275:11 in
```

This message comes from the fact that in https://github.com/thestk/rtmidi/blob/edb963b608c0b682a5154a35c898cc607d517dc9/RtMidi.cpp#L1275 `apiData->lastTime` can be bigger than `time`.

A workaround is then to change the line to `time -= std::min(time,  apiData->lastTime)`

This happened on my system which is linux (debian testing) using the alsa backend.

**Comment by radarsat1** [comment]
Seems the code referred to here was commented out and replaced, so hopefully fixed previously, but I just updated the time computation so I'm fairly sure this should be avoided as of c3328c0a83de96d96de15959ca21d6ba16219f92 since it is now the time difference method recommended by the GNU libc manual.
